const KeyMap = {
  Enter: 'ENTER',
  Left: 'LEFT',
  Right: 'RIGHT',
  Up: 'UP',
  Down: 'DOWN',
  Menu: 'MENU',
  Home: 'HOME',
  Exit: 'EXIT',
  Power: 'POWER',
  Back: 'BACK',
  Info: 'INFO',
  ChannelUp: 'CHANNELUP',
  ChannelDown: 'CHANNELDOWN',
  VolumeUp: 'VOLUMEUP',
  VolumeDown: 'VOLUMEDOWN',
  '0': '0',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  Dash: 'DASH',
  Asterisk: 'ASTERISK',
  Mute: 'MUTE',
  CC: 'CC',
  Red: 'RED',
  Green: 'GREEN',
  Blue: 'BLUE',
  Yellow: 'YELLOW',
};

export default KeyMap;
