const KeyMap = {
  Home: 'KEY_HOME',
  Enter: 'KEY_ENTER',
  Return: 'KEY_RETURN',
  Left: 'KEY_LEFT',
  Right: 'KEY_RIGHT',
  Up: 'KEY_UP',
  Down: 'KEY_DOWN',
  PowerOff: 'KEY_POWEROFF',
  ChannelUp: 'KEY_CHUP',
  ChannelDown: 'KEY_CHDOWN',
  ChannelList: 'KEY_CH_LIST',
  Menu: 'KEY_MENU',
  Source: 'KEY_SOURCE',
  Guide: 'KEY_GUIDE',
  Tools: 'KEY_TOOLS',
  Info: 'KEY_INFO',
  ARed: 'KEY_RED',
  BGreen: 'KEY_GREEN',
  CYellow: 'KEY_YELLOW',
  DBlue: 'KEY_BLUE',
  '3D': 'KEY_PANNEL_CHDOWN',
  VolumeUp: 'KEY_VOLUP',
  VolumeDown: 'KEY_VOLDOWN',
  Mute: 'KEY_MUTE',
  '0': 'KEY_0',
  '1': 'KEY_1',
  '2': 'KEY_2',
  '3': 'KEY_3',
  '4': 'KEY_4',
  '5': 'KEY_5',
  '6': 'KEY_6',
  '7': 'KEY_7',
  '8': 'KEY_8',
  '9': 'KEY_9',
  TvSource: 'KEY_DTV',
  HDMISource: 'KEY_HDMI',
  SmartHub: 'KEY_CONTENTS',
  Play: 'KEY_PLAY',
  Pause: 'KEY_PAUSE',
  Stop: 'KEY_STOP',
  Fastforward: 'KEY_FF',
  Rewind: 'KEY_REWIND',
};

export default KeyMap;
